FROM node:18

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .

ARG DATABASE_URL
ARG OPENAI_API_KEY
ARG NEXT_PUBLIC_PRIVY_APP_ID
ARG PRIVY_APP_SECRET
ARG NEXT_PUBLIC_DAILY_PROMPT_USAGE_LIMIT_PER_USER
ARG NEXT_PUBLIC_USER_REGISTRATION_CAP
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SOLANA_EXPLORER_URL
ARG NEXT_PUBLIC_SOLANA_NETWORK
ARG NEXT_PUBLIC_SOLANA_RPC_ENDPOINT
ARG NEXT_PUBLIC_TREASURY_WALLET
ARG SOLANA_ADMIN_PRIVATE_KEY
ARG SOLANA_ADMIN_PUBLIC_KEY

ENV DATABASE_URL=${DATABASE_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV NEXT_PUBLIC_PRIVY_APP_ID=${NEXT_PUBLIC_PRIVY_APP_ID}
ENV PRIVY_APP_SECRET=${PRIVY_APP_SECRET}
ENV NEXT_PUBLIC_DAILY_PROMPT_USAGE_LIMIT_PER_USER=${NEXT_PUBLIC_DAILY_PROMPT_USAGE_LIMIT_PER_USER}
ENV NEXT_PUBLIC_USER_REGISTRATION_CAP=${NEXT_PUBLIC_USER_REGISTRATION_CAP}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_SOLANA_EXPLORER_URL=${NEXT_PUBLIC_SOLANA_EXPLORER_URL}
ENV NEXT_PUBLIC_SOLANA_NETWORK=${NEXT_PUBLIC_SOLANA_NETWORK}
ENV NEXT_PUBLIC_SOLANA_RPC_ENDPOINT=${NEXT_PUBLIC_SOLANA_RPC_ENDPOINT}
ENV NEXT_PUBLIC_TREASURY_WALLET=${NEXT_PUBLIC_TREASURY_WALLET}
ENV SOLANA_ADMIN_PRIVATE_KEY=${SOLANA_ADMIN_PRIVATE_KEY}
ENV SOLANA_ADMIN_PUBLIC_KEY=${SOLANA_ADMIN_PUBLIC_KEY}

RUN pnpm build

CMD ["pnpm", "start"]