FROM node:18

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .

ARG NEXT_PUBLIC_PRIVY_APP_ID
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SOLANA_RPC_ENDPOINT
ARG NEXT_PUBLIC_SOLANA_NETWORK
ARG NEXT_PUBLIC_SOLANA_EXPLORER_URL
ARG NEXT_PUBLIC_TREASURY_WALLET
ARG NEXT_PUBLIC_DAILY_PROMPT_USAGE_LIMIT_PER_USER
ARG NEXT_PUBLIC_USER_REGISTRATION_CAP

ENV NEXT_PUBLIC_PRIVY_APP_ID=${NEXT_PUBLIC_PRIVY_APP_ID}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_SOLANA_RPC_ENDPOINT=${NEXT_PUBLIC_SOLANA_RPC_ENDPOINT}
ENV NEXT_PUBLIC_SOLANA_NETWORK=${NEXT_PUBLIC_SOLANA_NETWORK}
ENV NEXT_PUBLIC_SOLANA_EXPLORER_URL=${NEXT_PUBLIC_SOLANA_EXPLORER_URL}
ENV NEXT_PUBLIC_TREASURY_WALLET=${NEXT_PUBLIC_TREASURY_WALLET}
ENV NEXT_PUBLIC_DAILY_PROMPT_USAGE_LIMIT_PER_USER=${NEXT_PUBLIC_DAILY_PROMPT_USAGE_LIMIT_PER_USER}
ENV NEXT_PUBLIC_USER_REGISTRATION_CAP=${NEXT_PUBLIC_USER_REGISTRATION_CAP}

RUN pnpm build

CMD ["pnpm", "start"]