/* tslint:disable */
/* eslint-disable */
/**
 * LW RAG API
 * RAGシステムのAPI
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models';

export interface ReadItemItemsItemIdGetRequest {
    itemId: any;
    q?: any;
}

/**
 * ItemsApi - interface
 * 
 * @export
 * @interface ItemsApiInterface
 */
export interface ItemsApiInterface {
    /**
     * アイテム情報を取得。  Args:     item_id: アイテムID     q: クエリパラメータ（オプション）
     * @summary Read Item
     * @param {any} itemId 
     * @param {any} [q] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApiInterface
     */
    readItemItemsItemIdGetRaw(requestParameters: ReadItemItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * アイテム情報を取得。  Args:     item_id: アイテムID     q: クエリパラメータ（オプション）
     * Read Item
     */
    readItemItemsItemIdGet(requestParameters: ReadItemItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class ItemsApi extends runtime.BaseAPI implements ItemsApiInterface {

    /**
     * アイテム情報を取得。  Args:     item_id: アイテムID     q: クエリパラメータ（オプション）
     * Read Item
     */
    async readItemItemsItemIdGetRaw(requestParameters: ReadItemItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.itemId === null || requestParameters.itemId === undefined) {
            throw new runtime.RequiredError('itemId','Required parameter requestParameters.itemId was null or undefined when calling readItemItemsItemIdGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.q !== undefined) {
            queryParameters['q'] = requestParameters.q;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/items/{item_id}`.replace(`{${"item_id"}}`, encodeURIComponent(String(requestParameters.itemId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * アイテム情報を取得。  Args:     item_id: アイテムID     q: クエリパラメータ（オプション）
     * Read Item
     */
    async readItemItemsItemIdGet(requestParameters: ReadItemItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.readItemItemsItemIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
