name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # Wait for Postgres to be ready
        options: >-
          --health-cmd "pg_isready -U postgres -d test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up database URL
        run: echo "DATABASE_URL=postgresql://postgres:example@localhost:5432/test?schema=public" >> $GITHUB_ENV

      - name: Prisma Migrate (Deploy)
        run: pnpm prisma migrate deploy

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
