/* tslint:disable */
/* eslint-disable */
/**
 * LW RAG API
 * RAGシステムのAPI
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * コーパス作成のリクエストモデル。
 * @export
 * @interface CorporaCreate
 */
export interface CorporaCreate {
    /**
     * 
     * @type {any}
     * @memberof CorporaCreate
     */
    collectionName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CorporaCreate
     */
    csvPath?: any | null;
}

/**
 * Check if a given object implements the CorporaCreate interface.
 */
export function instanceOfCorporaCreate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CorporaCreateFromJSON(json: any): CorporaCreate {
    return CorporaCreateFromJSONTyped(json, false);
}

export function CorporaCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporaCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'collectionName': !exists(json, 'collection_name') ? undefined : json['collection_name'],
        'csvPath': !exists(json, 'csv_path') ? undefined : json['csv_path'],
    };
}

export function CorporaCreateToJSON(value?: CorporaCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'collection_name': value.collectionName,
        'csv_path': value.csvPath,
    };
}

