/* tslint:disable */
/* eslint-disable */
/**
 * LW RAG API
 * RAGシステムのAPI
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 主題の明確さ
 * @export
 * @interface SubjectClarity
 */
export interface SubjectClarity {
}

/**
 * Check if a given object implements the SubjectClarity interface.
 */
export function instanceOfSubjectClarity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectClarityFromJSON(json: any): SubjectClarity {
    return SubjectClarityFromJSONTyped(json, false);
}

export function SubjectClarityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectClarity {
    return json;
}

export function SubjectClarityToJSON(value?: SubjectClarity | null): any {
    return value;
}

