/* tslint:disable */
/* eslint-disable */
/**
 * LW RAG API
 * RAGシステムのAPI
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 文体
 * @export
 * @interface WritingStyle
 */
export interface WritingStyle {
}

/**
 * Check if a given object implements the WritingStyle interface.
 */
export function instanceOfWritingStyle(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WritingStyleFromJSON(json: any): WritingStyle {
    return WritingStyleFromJSONTyped(json, false);
}

export function WritingStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WritingStyle {
    return json;
}

export function WritingStyleToJSON(value?: WritingStyle | null): any {
    return value;
}

