/* tslint:disable */
/* eslint-disable */
/**
 * LW RAG API
 * RAGシステムのAPI
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ライタープロンプト設定
 * @export
 * @interface WriterPromptConfig
 */
export interface WriterPromptConfig {
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    systemPrompt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    writingPurpose?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    subjectClarity?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    breadcrumb?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    writingStyle?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    temporalAttitude?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    useBulletPoints?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WriterPromptConfig
     */
    useEmphasis?: any | null;
    /**
     * 合計文字数
     * @type {any}
     * @memberof WriterPromptConfig
     */
    totalCharacterCount?: any | null;
    /**
     * 箇条書き1項目あたりの文字数
     * @type {any}
     * @memberof WriterPromptConfig
     */
    bulletPointCharacterCount?: any | null;
    /**
     * 箇条書きの項目数
     * @type {any}
     * @memberof WriterPromptConfig
     */
    numberOfBulletPoints?: any | null;
}

/**
 * Check if a given object implements the WriterPromptConfig interface.
 */
export function instanceOfWriterPromptConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WriterPromptConfigFromJSON(json: any): WriterPromptConfig {
    return WriterPromptConfigFromJSONTyped(json, false);
}

export function WriterPromptConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriterPromptConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'systemPrompt': !exists(json, 'system_prompt') ? undefined : json['system_prompt'],
        'writingPurpose': !exists(json, 'writing_purpose') ? undefined : json['writing_purpose'],
        'subjectClarity': !exists(json, 'subject_clarity') ? undefined : json['subject_clarity'],
        'breadcrumb': !exists(json, 'breadcrumb') ? undefined : json['breadcrumb'],
        'writingStyle': !exists(json, 'writing_style') ? undefined : json['writing_style'],
        'temporalAttitude': !exists(json, 'temporal_attitude') ? undefined : json['temporal_attitude'],
        'useBulletPoints': !exists(json, 'use_bullet_points') ? undefined : json['use_bullet_points'],
        'useEmphasis': !exists(json, 'use_emphasis') ? undefined : json['use_emphasis'],
        'totalCharacterCount': !exists(json, 'total_character_count') ? undefined : json['total_character_count'],
        'bulletPointCharacterCount': !exists(json, 'bullet_point_character_count') ? undefined : json['bullet_point_character_count'],
        'numberOfBulletPoints': !exists(json, 'number_of_bullet_points') ? undefined : json['number_of_bullet_points'],
    };
}

export function WriterPromptConfigToJSON(value?: WriterPromptConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'system_prompt': value.systemPrompt,
        'writing_purpose': value.writingPurpose,
        'subject_clarity': value.subjectClarity,
        'breadcrumb': value.breadcrumb,
        'writing_style': value.writingStyle,
        'temporal_attitude': value.temporalAttitude,
        'use_bullet_points': value.useBulletPoints,
        'use_emphasis': value.useEmphasis,
        'total_character_count': value.totalCharacterCount,
        'bullet_point_character_count': value.bulletPointCharacterCount,
        'number_of_bullet_points': value.numberOfBulletPoints,
    };
}

